# Generated by Django 2.1.5 on 2019-02-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='creaated_at',
            new_name='created_at',
        ),
    ]
